class UserpageElement:
    account_tab = "/html/body/div/div/div/div[1]/nav/div[2]/ul[2]/li[3]"  # by XPath
    profile_tab = "/html/body/div/div/div/div[1]/nav/div[2]/ul[2]/li[2]"  # by XPath
    referrer_tab = "/html/body/div/div/div/div[1]/nav/div[2]/ul[2]/li[4]"  # by Xpath
    notification_tab = "/html/body/div/div/div/div[1]/nav/div[2]/ul[2]/li[5]"  # by XPath
    account_username_field = "nameField"  # by ID
    account_save_button = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[4]/div[2]/button"  # by XPath
    notification_notification = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/table/tbody/tr[1]/td[2]/div"  #  by XPath
    notification_details = "modal-content"  # by Class Name
    member_list_tab = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div[1]/ul/li[1]/a"  # by XPath
    member_list_details = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div[1]/div/table/tbody/tr[1]/td[1]/div"  # by XPath
    bet_record_tab = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div[1]/ul/li[2]/a"  # by Xpath
    bet_record_details = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div[2]/div[2]/div/table/tbody/tr[1]/td[1]"  # by Xpath
    report_tab = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/div[1]/ul/li[3]/a"  # by Xpath
    report_details = "card-body"  # by Class Name
    account_record_tab = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/ul/li[7]/a"  # by XPath
    account_rdeposit_tab = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/ul/li[1]/a"  # by Xpath
    account_rwithdrawal_tab = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[1]/ul/li[2]/a"  # by XPath
    account_deposit_details = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[1]/div/table/tbody/tr[1]/td[1]"  # by XPath
    account_withdrawal_details = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/div[2]/div[2]/div/table/tbody/tr[1]/td[1]"  # by XPath
    account_transfer_tab = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/ul/li[5]"  # by XPath
    account_deposit_tab = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/ul/li[1]"  # by XPath
    account_withdrawal_tab = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/ul/li[3]"  # by Xpath
    account_transfer_from = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div[2]/select"  # by XPath
    account_transfer_to = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[3]/div[2]/select"  # by Xpath
    account_transfer_amount_field = "amountField"  # by ID
    account_transfer_submit_button = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div[2]/div/div[4]/div[2]/button"  # by Xpath
    account_deposit_bank = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[3]/div/p/span[1]/div/div[1]/img"  # by XPath
    account_deposit_amount = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/span/div/div[4]/fieldset/div/div/label[1]"  # by XPath
    account_deposit_promotion = "custom-select-sm"  # by Class Name
    account_deposit_submit_button = "/html/body/div/div/div/div[2]/div[1]/div/div/div/div/div/div/div/div[2]/div/div[6]/div[2]/button"  # by XPath
    account_withdrawal_bank = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[2]/span/div/div[2]/div/select"  # by XPath
    account_withdrawal_amount = "number-100"  # by ID
    account_withdrawal_submit_button = "/html/body/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[5]/div[2]/button"  # by XPath