class MainpageElement:
    announcement_modal_dialog_close_button = "close"  # Class Name
    main_bottom_page = "footer-text"  # by Class Name
    about_us_link = "/html/body/div/div/div/div[3]/div/ul/li[1]/a"  # by Xpath
    about_us_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/p[2]" # by Class Name
    mobile_betting_link = "/html/body/div/div/div/div[3]/div/ul/li[2]/a"  # by XPath
    mobile_betting_qr = "col"  # by Class Name
    faq_link = "/html/body/div/div/div/div[3]/div/ul/li[3]/a"  # by XPath
    faq_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[2]/a" # by XPath
    faq_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/p[2]"  # by XPath
    deposit_help_link = "/html/body/div/div/div/div[3]/div/ul/li[4]/a"  # by XPath
    withdrawal_help_link = "/html/body/div/div/div/div[3]/div/ul/li[5]/a"  # by XPath
    bottom_link_title = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[1]/p"  # by XPath
    marquee_announcement = "marquee-text"  # by Class Name
    marquee_announcement_modal = "btn-block"  # by Class name
    loginNregistration_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[3]/a"  # by XPath
    loginNregistration_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/p[2]"  # by XPath
    basic_term_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[4]/a"  # by XPath
    basic_term_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/p[2]"  # by XPath
    deposit_process_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[5]/a"  # by XPath
    deposit_process_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[1]/p[2]"  # by XPath
    quick_deposit_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[2]/a"  # by XPath
    quick_deposit_details = "/html/body/div[1]/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[2]"  # by XPath
    online_banking_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[3]/a"  # by XPath
    online_banking_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    alipay_scancode_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[4]/a"  # by XPath
    alipay_scancode_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    wechat_scancode_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[5]/a"  # by XPath
    wechat_scancode_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    withdrawal_process_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[6]/a"  # by XPath
    withdrawal_process_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[1]"  # by XPath
    withdrawal_process_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[2]/a"  # by XPath
    withdrawal_process_tab_details = "/html/body/div[1]/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[2]/p[2]"  # by XPath
    moneytransfer_process_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[7]/a"  # by Xpath
    moneytransfer_process_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[1]/p[2]"  # by XPath
    moneytransfer_process_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[2]/a"  # by XPath
    moneytransfer_process_tab_details = "/html/body/div[1]/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[2]/p[1]"  # by XPath
    account_security_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[8]/a"  # by XPath
    account_security_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[1]"  # by XPath
    betting_rulesandregulation_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[2]/a"  # by XPath
    betting_rulesandregulation_details = "/html/body/div[1]/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div[2]/p[1]"  # by XPath
    betting_responsibility_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[3]/a"  # by XPath
    betting_responsibility_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    rulesandregulation_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[1]/ul/li[4]/a"  # by Xpath
    rulesandregulation_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    user_privacy_agreement_tab = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    user_privacy_agreement_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath
    online_problem_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[9]/a"  # by XPath
    online_problem_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/p[3]"  # by XPath
    agency_cooperation_button = "/html/body/div/div/div/div[2]/div[2]/div/div/div[1]/div/ul/li[10]/a"  # by XPath
    agency_cooperation_details = "/html/body/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]"  # by XPath