class UserElement:
    quota_conversion_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[1]/a"  # by XPath
    quota_conversion_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[1]/div/div[1]/a"  # by XPath
    deposit_area_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[2]/a"  # by XPath
    deposit_area_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[1]/div/span/span[1]/div/div/div/label[1]"  # by XPath
    withdrawal_area_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[3]/a"  # by XPath
    withdrawal_area_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/span/div[2]/button"  # by XPath
    funding_records_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[4]/a"  # by XPath
    funding_records_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[1]/a"  # by XPath
    betting_record_links = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[5]/a"  # by XPath
    betting_record_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/nav[1]/ul[1]/div[1]/div/input"  # by XPath
    member_agent_links = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[6]/a"  # by XPath
    member_agent_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[1]/a"  # by XPath
    announcement_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[7]/a"  # by XPath
    announcement_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/table/thead/tr/th[1]"  # by XPath
    personal_information_link = "/html/body/div[1]/div/div/div[2]/div/div/div/div[1]/div[2]/ul/li[8]/a"  # by XPath
    personal_information_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/a"  # by XPath
    quotaconversion_withdrawal_button = "btn-outline-dark"  # by Class Name
    quotaconversion_deposit_button = "btn-dark"  # by Class Name
    quotaconversion_confirm_transfer_button = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[2]/span/div/button"  # by XPath
    quotaconversion_amount_field = "nested-amount-input-3"  # by ID
    quotaconversion_evoamount = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[4]/div/div/div[1]/div/div/p"  # by XPath
    quotaconversion_accamount = "/html/body/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div[1]/p"  # by XPath
    deposit_area_deposit_method = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[1]/div/span/span[1]/div/div/div/label[1]"  # by XPath
    deposit_area_deposit_amount = "/html/body/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[1]/div/span/div[1]/div/div/label[1]"  # by XPath
    deposit_area_next_step_button = "btn-dark"  # by Class Name
    deposit_area_complete_deposit_button = "btn-dark"  # by Class Name
    withdrawal_area_select_bank = "/html/body/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/span/div[1]/span/div/div[1]/label/div"  # by XPath
    withdrawal_area_amount_field = "nested-amount-input-2"  # by ID
    withdrawal_area_next_step = "btn-dark"  # by Class Name
    withdrawal_area_add_bank = "/html/body/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/span/div[1]/a"  # by CSS
    withdrawal_area_account_name_field = "nested-name-input-1"  # by ID
    withdrawal_area_acc_number_field = "nested-number-input-2"  # by ID
    withdrawal_area_select_bank_drop_down = "nested-bank-select-3"  # by ID
    withdrawal_area_submit_button = "btn-dark"  # by Class Name
    withdrawal_area_reset_button = "btn-outline-dark"  # by Class Name
    funding_record_deposit_record = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[1]/a"  # by XPath
    funding_record_withdrawal_record = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[2]/a"  # by XPath
    funding_record_deposit_details = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[1]/div/table/tbody/tr[1]/td[1]"  # by Xpath
    funding_record_withdrawal_details = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/table/tbody/tr[1]/td[1]"  # by XPath
    member_agent_member_detail = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[1]/a"  # by Xpath
    member_agent_detail_report = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[2]/a"  # by XPath
    member_agent_betting_record = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[1]/ul/li[3]/a"  # by XPath
    member_agent_member_detail_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[1]/div/table/tbody/tr[1]/td[1]"  # by XPath
    member_agent_detail_report_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/div/div[1]/div/div"  # by XPath
    member_agent_betting_record_element = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/table/tbody/tr[1]/td[1]"  # by XPath
    announcement_details = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/table/tbody/tr[1]/td[1]"  # by XPath
    personal_info_modify = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[4]/div[4]/a"
    personal_info_actual_name = "nested-name-input-1"  # by ID
    personal_info_confirm_button = "btn-dark"  # by class name
    personal_info_change_password = "btn-sm"  # by Class Name
    personal_info_old_password = "nested-old"  # by ID
    personal_info_new_password = "nested-new"  # by ID
    personal_info_confirm_password = "nested-confirm"  # by ID
    personal_info_next_step = "btn-dark"  # by Class Name
    personal_info_password_modified = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/div/div/div"  # by XPath
    betting_record_choose_game_platform = "dropdown-toggle-no-caret"  # by Class Name
    betting_record_game_platform_video_all = "/html/body/div[1]/div/div/div[2]/div/div/div/div[2]/div[2]/div/nav[1]/ul[2]/div/ul/li[3]/ul/div/div[1]/li/button"  # by XPath